### PR TITLE
Fix incorrect CSS (breaking)

### PR DESCRIPTION
**Pull request by dvsmc**
1. Various style loaders detect incorrect css and fails.
2. Fixed invalid CSS in general.

### CODE REVIEW

**Review by nosovk — APPROVED** [review]

**Comment by dvsmc** [comment]
@nosovk please merge when you can

**Comment by nosovk** [comment]
I have no access to merge, I think that only @antony can

**Comment by nosovk** [comment]
Actually I was doing https://github.com/beyonk-group/svelte-notifications/pull/48 and just checked other PRs to verify that nobody else have done that before, and saw your PR which seems good to me

**Comment by nosovk** [comment]
you may use 
`npm i github:nosovk/svelte-notifications#fixup`
which has your fix and also changes from my branch precompiled. It's a temporary solution, but it works for now.

**Pull request closed without merging**
